# Generated by Django 4.0 on 2021-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=400)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
